server:
  port: 8080

sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8082
    inventory-user: good
    inventory-password: beer

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml